decoder_number: 32
hp: !!python/object:argparse.Namespace
  act: false
  act_loss_weight: 0.001
  basic_learner: true
  batch_size: 128
  beam_size: 5
  cuda: true
  data_dir: data/ED
  decoder: single
  depth: 40
  devices: 0,1,2,3
  emb_dim: 300
  emb_file: null
  emo_combine: gate
  emo_input: self_att
  emotion_emb_type: origin
  eq6_loss: false
  filter: 50
  heads: 2
  hidden_dim: 300
  hop: 1
  init_emo_emb: false
  is_coverage: false
  l1: 0.0
  label_smoothing: true
  large_decoder: false
  lr: 0.0001
  max_grad_norm: 2.0
  mean_query: false
  mode: only_test
  model: mult
  model_path: save/test
  multitask: false
  noam: true
  oracle: false
  pointer_gen: false
  pretrain_emb: true
  project: false
  save_path: save/test
  save_path_dataset: save/
  schedule: 10000
  seed: 42
  softmax: true
  test: false
  topk: 5
  universal: false
  use_oov_emb: false
  vader_loss: false
  vae: false
  weight_sharing: false
  woCOG: false
  woDiv: false
  woEMO: false
is_multitask: true
